--1
SELECT DEPARTMENT_NAME 학과명, CATEGORY 계열
FROM TB_DEPARTMENT TD;

--2
SELECT DEPARTMENT_NAME ||'의 정원은 '|| CAPACITY || '명 입니다.' "학과별 정원"
FROM TB_DEPARTMENT TD;

--3
SELECT STUDENT_NAME
FROM TB_STUDENT TS 
JOIN TB_DEPARTMENT TD USING(DEPARTMENT_NO)
WHERE ABSENCE_YN = 'Y' AND TD.DEPARTMENT_NAME = '국어국문학과' AND
SUBSTR(TS.STUDENT_SSN,8,1) = '2' ;

--4
SELECT STUDENT_NAME 
FROM TB_STUDENT TS 
WHERE STUDENT_NO IN('A513079','A513090','A513091','A513110','A513119')
ORDER BY STUDENT_NAME DESC;


--5
SELECT DEPARTMENT_NAME , CATEGORY 
FROM TB_DEPARTMENT TD 
WHERE CAPACITY BETWEEN 20 AND 30;

--6
SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR TP 
WHERE DEPARTMENT_NO IS NULL;

--7
SELECT *
FROM TB_STUDENT TS 
WHERE DEPARTMENT_NO IS NULL;
-- DEPARTMENT_NO NOT NULL인데 NULL이 있을 수 있나?

--8 
SELECT CLASS_NO 
FROM TB_CLASS TC2 
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT TD2;

--10
SELECT STUDENT_NO , STUDENT_NAME  , STUDENT_SSN 
FROM TB_STUDENT
WHERE ABSENCE_YN ='N'
AND STUDENT_NO LIKE 'A2%'
AND STUDENT_ADDRESS LIKE '%전주%'
ORDER BY STUDENT_NAME;