--1
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') 입학년도
FROM TB_STUDENT TS 
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ;

--2
SELECT PROFESSOR_NAME , PROFESSOR_SSN
FROM TB_PROFESSOR TP 
WHERE LENGTH(PROFESSOR_NAME) != 3;

--3
SELECT PROFESSOR_NAME 교수이름,
FLOOR(MONTHS_BETWEEN(SYSDATE,TO_DATE('19'||SUBSTR(PROFESSOR_SSN,1,6)))/12) AS 나이
FROM TB_PROFESSOR TP 
WHERE SUBSTR(PROFESSOR_SSN,8,1)=1
ORDER BY 2 ASC;

--4
SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;

--5
SELECT STUDENT_NO , STUDENT_NAME
FROM TB_STUDENT TS
WHERE  EXTRACT(YEAR FROM ENTRANCE_DATE)-
EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6)))>=20;

--6
SELECT TO_CHAR(TO_DATE('20201225'),'DAY') "2020년 크리스마스는 무슨 요일인가?"
FROM DUAL;

--7
SELECT TO_DATE('99/10/11','YY/MM/DD'),
TO_DATE('49/10/11','YY/MM/DD'),
TO_DATE('99/10/11','RR/MM/DD')
FROM DUAL;

--8
SELECT STUDENT_NO , STUDENT_NAME  
FROM TB_STUDENT TS
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

--9
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_STUDENT TS 
NATURAL JOIN TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10
SELECT DEPARTMENT_NO "학과번호", COUNT(DEPARTMENT_NO) "학생수(명)"
FROM TB_STUDENT TS 
GROUP BY DEPARTMENT_NO 
ORDER BY 1;

--11
SELECT COUNT(*)
FROM TB_STUDENT TS
WHERE COACH_PROFESSOR_NO IS NULL;

--12
SELECT SUBSTR(TERM_NO,1,4) 학과코드명,ROUND(AVG(POINT),1) "휴학생 수"
FROM TB_STUDENT TS
NATURAL JOIN TB_GRADE TG
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY SUBSTR(TERM_NO,1,4);

--13
SELECT DEPARTMENT_NO "학과코드명",SUM(DECODE(ABSENCE_YN,'Y',1,'N',0)) "휴학생 수"
FROM TB_STUDENT TS 
GROUP BY DEPARTMENT_NO
ORDER BY 1;

SELECT DEPARTMENT_NO "학과코드명", COUNT(CASE WHEN ABSENCE_YN='Y' THEN '배고파' END) "휴학생 수"
FROM TB_STUDENT TS
GROUP BY DEPARTMENT_NO
ORDER BY 1;


--14
SELECT STUDENT_NAME 동일이름, COUNT(*) "동일인 수"
FROM TB_STUDENT TS
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY 1;

--15
SELECT SUBSTR(TG.TERM_NO,1,4) 년도,SUBSTR(TG.TERM_NO,5,2) 학기, ROUND(AVG(TG.POINT),1) 평점
FROM TB_STUDENT TS
NATURAL JOIN TB_GRADE TG
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TG.TERM_NO,1,4),SUBSTR(TG.TERM_NO,5,2))
ORDER BY 1,2;